language: bash
services: docker

install:
    - git clone https://github.com/docker-library/official-images.git ~/official-images

before_script:
    - cp config/database_example.yml config/database.yml
    - cp config/secrets_example.yml config/secrets.yml
    - cp config/branding_example.yml config/branding.yml
    - cp config/initializers/devise.rb.example config/initializers/devise.rb
    - cp config/initializers/recaptcha.rb.example config/initializers/recaptcha.rb
    - cp config/initializers/wicked_pdf.rb.example config/initializers/wicked_pdf.rb
    - image="ualbertalib/DMP_roadmap"

script:
    - docker build -t "$image" .
    - ~/official-images/test/run.sh "$image"

after_script:
    - docker images
