version: '2.1'

volumes:
  db:

services:

  db:
    image: mysql
    env_file: .env
    healthcheck:
      test:  mysqladmin -uroot -p${MYSQL_ROOT_PASSWORD} ping
      interval: 5s
      timeout: 5s
      retries: 100

    volumes:
      - db:/var/lib/mysql

  web:
    build: .
    image: ualbertalib/dmp_roadmap
    env_file: .env
    command: bash -c 'rm -f tmp/pids/server.pid && rake db:migrate && rails s -p 3000 -b "0.0.0.0"'
    volumes:
      - .:/app
    depends_on:
      db:
        condition: service_healthy

    ports:
      - 3000:3000

